import { AtlasVisual } from '@/components/atlas-visual';
import { PageStructuredData } from '@/components/structured-data'; import { FaqSection } from '@/components/faq-section'; import { publicFaqs } from '@/content/public-faq';
import { pageMetadata } from '@/content/seo';
import type { Metadata } from 'next'; import { PlatformStory } from '@/components/platform-story'; import { SiteFooter, SiteHeader } from '@/components/site-shell'; import { RADAR_URL, capabilityLabels, productCapabilities } from '@/content/product-truth';
import { Cta, PageHero, Rows, Section, TextLink } from '@/components/kit';
export const metadata: Metadata = pageMetadata({ path: '/piattaforma', title: 'Horyzon Platform', description: 'Uno spazio dedicato per rendere visibili priorità, lavoro e avanzamento della tua impresa.' });
// Hero with an illustrative window (ink) → four layers (cream) → what is available, configured or a direction (panel)
// → the configuration note on the lime field → FAQ.
export default function PlatformPage(){return <><PageStructuredData path="/piattaforma" name="Horyzon Platform" description="Uno spazio dedicato per rendere visibili priorità, lavoro e avanzamento della tua impresa." breadcrumbs={[{ name: 'Horyzon', path: '/' }, { name: 'Come lavoriamo', path: '/metodo' }, { name: 'Platform', path: '/piattaforma' }]} faqs={publicFaqs['/piattaforma']} /><SiteHeader/><main id="content" className="rd rd-page editorial-page narrative-page" data-page="piattaforma">
 <PageHero crumbs={[{ name: 'Horyzon', href: '/' }, { name: 'Come lavoriamo', href: '/metodo' }, { name: 'Platform' }]} label="Horyzon / Platform" title={<>Vedi ciò che serve <em>per decidere.</em></>} lead="Quando il percorso lo richiede, la Platform rende condivise priorità, avanzamento e informazioni utili all’azienda." aside={<AtlasVisual kind="platform" />}><Cta href="#percorso-platform" arrow="↓">Scopri la Platform</Cta><TextLink href={RADAR_URL}>Inizia dal Radar ↗︎</TextLink></PageHero>
 <Section id="percorso-platform" tone="cream" label="Uno spazio condiviso" title="Le informazioni giuste, al momento giusto." lead="La Platform non sostituisce le persone: le aiuta a vedere insieme ciò che è prioritario e a seguire il lavoro nel tempo." headingId="platform-spazio"><PlatformStory/></Section>
 <Section tone="panel" split label="Quando serve" title="Ogni impresa ha il suo punto di partenza." headingId="platform-quando"><Rows ordered={false} items={productCapabilities.map(capability => ({ tag: capabilityLabels[capability.state], lit: capability.state === 'available', title: capability.title, text: capability.description }))} /></Section>
 <section className="rd-section rd-tone-lime"><p className="rd-statement" style={{ maxWidth: '34ch', fontSize: 'clamp(24px,2.6vw,40px)' }}>La Platform viene configurata nel percorso Horyzon: accessi, integrazioni e informazioni disponibili dipendono dalle esigenze e dalle verifiche di ogni azienda.</p><div className="rd-actions"><Cta href="/metodo">Scopri come lavoriamo</Cta><TextLink href="/contatti">Parliamone ↗︎</TextLink></div></section>
 <FaqSection items={publicFaqs['/piattaforma']} />
</main><SiteFooter/></>}
