import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
const pages: Record<string, { kicker:string; title:string; intro:string; body:string[]; points:string[] }> = {
  "benessere-organizzativo": { kicker:"01 · Imprese", title:"Un'azienda cresce quando crescono le persone che la compongono.", intro:"Rendiamo visibili dinamiche, responsabilità e priorità per costruire organizzazioni più autonome, solide e capaci di evolvere.", body:["Ogni problema organizzativo lascia segnali: decisioni che si accumulano, ruoli poco chiari, talenti che non esprimono il proprio potenziale.","Horyzon parte dall'ascolto e dalla misura. Costruiamo un percorso concreto che unisce analisi organizzativa, sviluppo imprenditoriale e human management."], points:["Analisi organizzativa","Sviluppo imprenditoriale","Human management"] },
  "benessere-patrimoniale": { kicker:"02 · Professionisti e imprenditori", title:"Il patrimonio deve lavorare per la tua libertà.", intro:"Costruiamo una visione patrimoniale integrata, comprensibile e coerente con la persona, la famiglia e l'impresa.", body:["Il patrimonio non è una somma di prodotti. È il risultato di anni di lavoro, decisioni e responsabilità.","Partiamo dagli obiettivi e rendiamo leggibili rischi, opportunità e alternative, coordinando le competenze necessarie."], points:["Visione patrimoniale","Imprenditori","Professionisti"] },
  "benessere-digitale": { kicker:"03 · Sistema Paese", title:"L'intelligenza artificiale diventa lavoro migliore.", intro:"Portiamo AI, automazioni e dati nei processi reali per liberare tempo, ridurre inefficienze e migliorare le decisioni.", body:["Non partiamo dalla tecnologia. Partiamo dal lavoro che oggi rallenta l'azienda, disperde informazioni o dipende troppo dalle singole persone.","Disegniamo un'evoluzione graduale: comprensibile per chi la usa, misurabile per chi guida e sicura per tutta l'organizzazione."], points:["Strategia AI","Automazione dei processi","Dati e decisioni"] },
  "horyzon": { kicker:"La nostra direzione", title:"Talento che diventa servizio. Crescita che diventa possibilità.", intro:"Horyzon riunisce competenze diverse intorno a una missione: rendere più forti le imprese, l'economia e le persone.", body:["Crediamo in un'Italia capace di trasformare creatività, lavoro e conoscenza in benessere condiviso.","Per questo osserviamo ogni impresa come un sistema completo: organizzazione, patrimonio e tecnologia non sono mondi separati."], points:["Impresa","Economia","Umanità"] },
  "umanita": { kicker:"La persona al centro", title:"Corpo, mente e spirito. Un'unica direzione interiore.", intro:"La tecnologia moltiplica le possibilità. Sono le persone a dare loro significato.", body:["Energia e azione, comprensione e decisione, significato e aspirazione: coltiviamo persone unite, centrate e allineate sul sogno.","Il nostro futuro non riduce l'umano a una funzione. Gli restituisce spazio per creare, scegliere e contribuire."], points:["Energia","Comprensione","Significato"] },
  "entra-in-horyzon": { kicker:"Partner Network", title:"Una casa professionale. Molte competenze. Una missione comune.", intro:"Per professionisti autonomi che vogliono crescere, contribuire ai progetti e collaborare con altri specialisti.", body:["Horyzon è una rete strutturata, professionale e umana che permette a ogni talento di mantenere la propria autonomia e moltiplicare il proprio impatto.","Cerchiamo persone che condividano responsabilità, ambizione e desiderio di servire gli altri attraverso il proprio lavoro."], points:["Crescere","Contribuire","Collaborare"] },
  "contatti": { kicker:"Costruiamo il prossimo passo", title:"Raccontaci il problema che vuoi risolvere.", intro:"In un primo confronto verifichiamo obiettivi, priorità e prossimo passo possibile.", body:["Non serve avere già una soluzione. È sufficiente partire da ciò che oggi assorbe tempo, limita la crescita o rende più difficili le decisioni.","Scrivici: il nostro primo compito sarà capire."], points:["info@horyzon.it","talenti@horyzon.it","Milano · Lugano · Bari"] },
};
export function generateStaticParams(){ return Object.keys(pages).map(slug=>({slug})); }
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const p=pages[slug];return p?{title:p.kicker,description:p.intro}:{};}
export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=pages[slug];if(!p)notFound();return <main className="inside"><header className="inside-nav"><Link href="/" className="wordmark"><span className="mark">H</span><span>HORYZON</span></Link><Link href="/">← Torna alla visione</Link></header><section className="inside-hero"><p className="eyebrow"><span/>{p.kicker}</p><h1>{p.title}</h1><p>{p.intro}</p></section><section className="inside-body"><div>{p.body.map(x=><p key={x}>{x}</p>)}</div><aside>{p.points.map((x,i)=><div key={x}><span>0{i+1}</span>{x}</div>)}</aside></section><section className="inside-cta"><p>Il cambiamento comincia da una conversazione.</p><a href="mailto:info@horyzon.it" className="button primary">Parliamone ↗</a></section></main>}
