import { ANNUNCI10X_AI_OUTPUT_SCHEMAS } from '../schemas.ts';
import { renderPrompt } from './helpers.ts';
import type { Annunci10xPromptDefinition } from './types.ts';

export const ANNUNCI10X_GENERATE_PROMPT_VERSION = 'annunci10x.generate.v33';

const invariants = [
  'Generate the Master ad only from the canonical Truth Ledger: confirmed/publishable RoleCard facts, RoleProfile, and CommunicationStrategy.',
  'Use groundedNarrativePlan as the internal map between strategy and prose. It defines the narrative blocks, supporting facts, allowed interpretations, and boundaries for broad copy.',
  'Use groundedNarrativePlan.facts as the evidence plan. Only KNOWN_FACT and MUST_MENTION_FACT entries are factual evidence; DO_NOT_INVENT entries are absent/unknown information and must never be completed by inference.',
  'Every substantial sentence must be internally traceable to evidenceRefs as DIRECT, PARAPHRASE, or COMPOSITION of multiple evidence facts. There is no category for professionally plausible knowledge.',
  'If an evidence fact names an activity but not its object, system, document, downstream process, or consequence, keep the sentence at the named activity level. Do not add the missing object from professional common sense.',
  'For every paragraph, develop only the meaning of facts listed in the relevant Grounded Narrative Plan block. A paragraph may be expansive, but its entities, processes, tools, responsibilities, conditions, and consequences must stay inside that block.',
  'Do not use Draft 0, do not reconstruct the Truth Ledger from generated text, and do not ask EXTRACT to reinterpret internally generated copy.',
  'Act as a senior recruiter and recruiting copywriter, not as a formatter of RoleCard fields.',
  'The final Master is a publishable recruiting ad: simple, human, professional, descriptive, and ready to copy into a job board.',
  'Write prose-first. The default output is connected Italian recruiting copy, not a fact sheet, HR card, numbered checklist, or RoleCard rendered with nicer labels.',
  'The reader should meet the job before they meet a list. Explain the work and the candidate fit in prose before using any compact scan aid.',
  'Do not compress a rich Truth Ledger into a short summary. Use confirmed facts to explain the job until a candidate can picture the work.',
  'A source-rich CREATE output must feel like a finished paid rewrite, not a concise internal summary. If the ledger contains role context, several responsibilities, requirements, conditions, and compensation, develop them into a substantial ad using only confirmed facts.',
  'For source-rich CREATE outputs, do not stop at a compact ad around 250-350 words. Unless the Truth Ledger is sparse, the Master should usually exceed 450 words and often land around 550-800 words, with every added sentence grounded in the plan.',
  'For source-rich CREATE outputs, build breadth before finalizing: opening/context normally 100-160 words, responsibilities/work reality 230-360 words, requirements/candidate fit 110-180 words, and conditions enough to be clear. These are guardrails, not padding targets.',
  'Do not try to expose every internal field. Use non-critical intelligence to improve the writing, and publish only facts that help the candidate decide.',
  'Do not receive or use target score, original score, price, payment state, or entitlement state.',
  'The goal is not to make the ad sound more promotional. The goal is to help a candidate understand and imagine the real work.',
  'No new facts, requirements, benefits, metrics, tools, company claims, career promises, work rhythms, frequencies, people, or conditions.',
  'Positive grounding rule: you may explain why a confirmed fact matters, but you may not complete the world around that fact with plausible adjacent details.',
  'Do not add safety, compliance, PPE, hazard, regulatory, procedure, or "in sicurezza" claims unless the Truth Ledger explicitly confirms them.',
  'Do not name logistics documents such as DDT, bolle, documenti di trasporto, delivery notes, or order documents unless the Truth Ledger explicitly names them.',
  'Do not add packaging, packing, wrapping, boxing, or "confezionamento/imballaggio" duties unless the Truth Ledger explicitly confirms them.',
  'Preserve named tools exactly. If the Truth Ledger names "transpallet", write "transpallet"; do not replace it with a generic tool phrase.',
  'Do not turn Git, code review, or team collaboration into release coordination, deployment ownership, or regular ceremonies unless those duties are explicitly confirmed.',
  'Do not add testing, QA, test automation, test cases, or "controlli applicativi" unless the Truth Ledger explicitly confirms testing duties.',
  'Do not add external services, client-service discrepancies, end-to-end ownership, regression prevention, or production incident scope unless the Truth Ledger explicitly confirms them.',
  'You may connect confirmed facts editorially, but never invent chronology, frequency, causality, or a typical day that the source does not support.',
  'Avoid frequency phrases such as "attivita quotidiana", "ogni giorno", "regolarmente", or "spesso" unless the Truth Ledger explicitly confirms that cadence.',
  'Candidate-facing copy must never mention the source document or internal process: no references to the ad, source text, page, score, rubric, validation, Annunci 10X, publication readiness, or internal data conflicts.',
  'If a fact is unresolved, contradictory, uncertain, or not publishable, omit it from candidate-facing copy. Do not explain the uncertainty inside the Master and do not choose the most plausible value.',
  'Missing information generates no candidate-facing text. Never write "non dichiarato", "non specificato", "non disponibile", "non sono stati dichiarati", or equivalent missing-data disclosures.',
  'Preserve required and preferred requirements semantically and keep unnecessary barriers out. TRAINABLE facts remain internal intelligence unless another confirmed public fact explicitly supports candidate-facing wording.',
  'Use public requirement wording that preserves classification without changing perceived strictness. Prefer "Requisiti richiesti" or "Cosa serve"; do not use "Requisiti selettivi" for REQUIRED facts.',
  'PREFERRED facts may be published as preferibile, gradito, plus, non obbligatorio, or a similar non-mandatory candidate-facing formulation. TRAINABLE facts are different: they must not become "imparerai", "ti insegneremo", "non serve", "si apprende", "utile familiarità", "conoscenza utile", or public training promises unless a separate confirmed public fact explicitly supports that exact assertion.',
  'Tie soft skills to the concrete activity, responsibility, interaction, or condition that makes them relevant when that link is supported.',
  'A candidate-fit section that only enumerates soft skills is under-developed when the Truth Ledger contains the activities that make those qualities matter. Explain the relationship using confirmed responsibilities and interactions.',
  'Represent routine, pressure, shifts, travel, physical effort, responsibility, and other demanding conditions faithfully when confirmed. Do not glamourize routine and do not hide difficulty.',
  'Use only concrete, supportable reasons to consider the offer. Do not add generic prestige, culture, growth, or employer-brand slogans.',
  'Do not invent application process facts: no LinkedIn, CV, presentation letter, interviews, callbacks, next steps, selection stages, or response timing unless the Truth Ledger explicitly states them.',
  'Every generated section must be traceable through sourceFactIds/sourcePaths to facts actually supplied in the input.',
  'Preserve confirmed compensation ranges, variable components, hybrid-work details, and application instructions exactly in meaning; do not shorten "30.000-36.000" to "30".',
  'Every paragraph must add a distinct supported fact or a distinct supported relationship between facts. Remove repetition before removing useful detail.',
  'Omit optional sections when there is no real source content. Prefer a shorter truthful ad over padded copy.',
  'TITLE is structural: put the job title in title and use an empty string for body. Never duplicate the title in body.',
  'Every section title must be a non-empty candidate-facing heading. Do not use an empty section title to avoid a forbidden internal label; choose a natural public heading instead.',
  'Do not include both OPENING and MISSION when they communicate the same candidate-facing idea. Keep only the section that adds the clearest distinct supported value.',
  'A bounded onboarding/training fact stays bounded. For example, two weeks of shadowing must never become regular, ongoing, recurring, or permanent interaction.',
  'If confirmed shifts or on-call availability are present, including negative values such as no shifts/no on-call, state them explicitly in CONDITIONS because they are candidate compatibility facts.',
  'A confirmed mission/outcome must remain explicitly visible in candidate-facing copy. Do not delete it merely to reduce repetition; instead remove the redundant wording around it.',
  'When confirmed, company context, operating context, autonomy, and unexpected events/variability are real-work facts. Surface them concretely without inventing cadence or chronology.',
  'sourceFactIds are traceability metadata only. A fact counts as preserved only when its meaning is actually visible in candidate-facing text.',
  'Dedicated RoleCard fields are canonical for location, work mode, contract, schedule, shifts, on-call availability, compensation, and application instructions. If a narrative field contains a different shadow value, ignore that shadow value and publish only the canonical dedicated field.',
] as const;

export const GENERATE_PROMPT: Annunci10xPromptDefinition = {
  id: 'annunci10x.generate',
  version: ANNUNCI10X_GENERATE_PROMPT_VERSION,
  operationType: 'GENERATE',
  outputSchema: ANNUNCI10X_AI_OUTPUT_SCHEMAS.GENERATE,
  instructions: renderGeneratePrompt(),
  invariants,
};

export function renderGeneratePrompt(): string {
  return [
    renderPrompt(
      'GENERATE',
      'Write a premium candidate-facing job ad from confirmed facts: clear enough to publish, natural enough to be read by a real candidate, and disciplined enough to avoid invented claims.',
      invariants,
    ),
    '',
    'Editorial construction:',
    '- Read groundedNarrativePlan before writing. Treat its blocks as the only authorized narrative plan: paragraphGoal tells you what to do, supportingFactIds tells you which facts support it, allowedInterpretations tells you how far you may develop meaning, and disallowedAdditions marks the boundary.',
    '- Use the block supportingFactIds as evidenceRefs. A generated claim may be DIRECT (same fact), PARAPHRASE (same meaning), or COMPOSITION (a narrative connection between multiple listed facts). Do not write claims that cannot name their evidenceRefs.',
    '- sourceFactIds should prefer the stable evidence IDs from groundedNarrativePlan.facts when available, so validation can trace the section back to Fxx facts.',
    '- The plan is internal. Do not mention "Grounded Narrative Plan", block ids, sourceFactIds, allowed interpretations, disallowed additions, or any planning language in candidate-facing copy.',
    '- TITLE: use a recognizable, search-friendly role title. Add specialization/location only when supported and useful. The TITLE section body must be an empty string; the title field is the visible title.',
    '- For every non-TITLE section, the title field must be non-empty. Use natural headings such as "Il ruolo", "Cosa farai", "Cosa serve", "Condizioni", or "Come candidarsi" when appropriate.',
    '- OPENING: use 2-3 natural, role-specific sentences. Within the first lines, make clear which role it is, which concrete context the person enters, and what characterizes the work. When a publishable companyDescription exists, include it here or in the first work paragraph; do not drop it during summarization. Do not default to "Siamo una PMI italiana e cerchiamo..." when richer supported facts are available.',
    '- OPENING must not duplicate RESPONSIBILITIES. Use it for role context, work purpose, and why the role matters. Put detailed tasks, tools, handoffs, and problems in RESPONSIBILITIES.',
    '- Do not create public sections called "Missione del ruolo" or "Obiettivo del ruolo". If a mission/outcome is confirmed, weave it into the opening or the work description as a natural sentence.',
    '- RESPONSIBILITIES: build an operating picture from confirmed activities. Show relationships, handoffs, or phases only when supported. Prefer short narrative paragraphs. Do not add a separate "Attivita principali" bullet section that repeats the same work already explained in prose.',
    '- RESPONSIBILITIES should usually be the richest part of the ad. Develop the work across multiple connected paragraphs when the facts allow it: what starts the work, what the person checks or produces, what happens when something does not line up, and who they coordinate with. Do not invent a rigid day-in-the-life, schedule, cadence, or sequence; but when the facts describe an obvious operating flow, make that flow understandable.',
    '- For warehouse/logistics roles with confirmed source facts, develop incoming goods, quantity checks, warehouse organization, order preparation, physical effort or transpallet use, coordination with drivers/order office, reliability, precision, teamwork, preferred experience/licences, and conditions. Keep each detail at the exact supported level: do not add product-condition checks, delivery/consegna scope, urgent peaks, procedures, documents, packaging, or safety unless those facts are in the plan.',
    '- For full-stack or software roles with confirmed source facts, develop separate paragraphs for product/development work, debugging and quality of the code, collaboration, stack/tools, and conditions. Do not turn these into requirement clarification, solution design, integration verification, architecture, regressions, QA/testing, releases/deploy, external services, endpoints, query work, or other technical ecosystem details unless those facts are explicitly in the plan.',
    '- CONTEXT: do not create a default "Contesto operativo" section just because internal context exists. Fold interactions, tools, autonomy, consequences of errors, and variability into the opening, responsibilities, or requirements when that reads more naturally.',
    '- REQUIREMENTS: distinguish truly selective requirements, preferences, and personal qualities inside a short candidate-fit paragraph. Do not publish subheadings such as "Requisiti principali", "Requisiti richiesti", "Requisiti preferiti", "Requisiti obbligatori", "Plus", or "(obbligatori)" followed by bullets unless the source is too dense to remain readable in prose. For simple roles, explain why the few requirements matter in the work. PREFERRED facts may appear as preferibile, gradito, plus, or non obbligatorio; TRAINABLE/internal-learning facts must not move into the public Master as preferences, non-barriers, useful familiarity, extra selection criteria, or training promises. Do not publish empty categories, "Preferenze: non dichiarate", "Trainabile", "Apprendibili", "Apprendibile sul posto", "Elementi apprendibili in sede", "Conoscenze che si apprendono sul posto", or "Formabili in sede" as headings or field labels.',
    '- REQUIREMENTS / CANDIDATE FIT: do not leave candidate fit as "affidabile, puntuale, preciso, lavoro di squadra" or another soft-skill inventory when responsibilities are available. Explain why those qualities matter in the confirmed work: quantity checks, order preparation, physical handling, error signalling, teamwork with declared interlocutors, or equivalent role-specific facts. Keep preferred requirements simply graditi/non obbligatori; do not invent their effects.',
    '- CONDITIONS: make confirmed location, work mode, contract, schedule, travel, availability, and compensation easy to find. Omit missing shifts/on-call/schedule/benefit facts instead of saying they are missing.',
    '- OFFER/GROWTH: include only concrete and verifiable support, onboarding, benefits, stability, flexibility, equipment, training, compensation, or growth facts. Preserve stated training/onboarding duration exactly in meaning; do not turn a limited period into an ongoing relationship.',
    '- APPLICATION: when a specific email/link/process exists, state it. If the only confirmed instruction is generic application through the channel, use exactly a neutral CTA such as "Se pensi che questa posizione possa essere adatta a te, inviaci la tua candidatura" without inventing requested documents, experience summaries, availability, steps, email, interviews, timing, or saying "canale dell annuncio" / "canale dell\'annuncio" / "canale indicato nell annuncio" / "nell\'annuncio".',
    '',
    'Candidate-facing voice:',
    '- Write as the final employer-facing job ad. Never say "l annuncio", "il testo", "la pagina", "il portale indica", "dato da chiarire", "prima della pubblicazione", or describe internal QA/scoring decisions.',
    '- Do not expose contradictions or missing-data analysis to the candidate. Leave unresolved facts out; downstream validation/gating handles them.',
    '- Do not use headings copied from internal fields: "Missione del ruolo", "Obiettivo del ruolo", "Contesto operativo e autonomia", "Autonomia", "Imprevisti e variabilita", "Apprendibili", "Apprendibile sul posto", "Elementi apprendibili in sede", "Conoscenze che si apprendono sul posto", "Trainabile", "Formabili in sede", "Vincoli", "negative constraints", or "Preferenze". Transform those ideas into prose.',
    '- Speak directly to the candidate when useful, but do not start every paragraph with "ti occuperai" or "dovrai". Vary sentence structure naturally.',
    '- Use explanatory sentences such as "Una parte importante del lavoro sara...", "Quando...", "Nel corso delle attivita...", "In questo ruolo...", "Ti troverai a...", and "Sara importante..." only when the relationship follows directly from confirmed facts.',
    '- Avoid the common HR template "Il ruolo / Cosa farai / Cosa serve / Condizioni / Come candidarsi" when it merely creates buckets. If those headings are used, each section must still read as prose with relationships, not as a list pasted under a label.',
    '- Never use malformed or internal-sounding headings such as "Il ruolo è il contesto". Use plain candidate headings such as "Il ruolo", "Il ruolo e il contesto", "Cosa farai", "Cosa serve", or a more natural role-specific heading.',
    '- Avoid repeated template transitions such as "questo significa che", "non si tratta solo di", or "una parte del lavoro". Use them only when they add a specific factual relationship.',
    '- If a paragraph could fit an unrelated role after swapping only the job title, rewrite it to be more role-specific or delete it.',
    '- Vary editorial rhythm by role. A warehouse role and a full-stack developer role should not share the same section sequence, cadence, or sentence pattern unless the facts genuinely call for it.',
    '',
    'Structure and density:',
    '- Do not force the same headings on every role. Choose the smallest set of sections that makes this role easy to understand, usually 3-6 candidate-facing sections.',
    '- Merge tiny adjacent sections when they explain the same decision. Avoid a heading followed by only one generic sentence.',
    '- Each section must answer a candidate question: what is this role, what will I actually do, what result matters, who/what do I interact with, what must I bring, what conditions will I accept, why consider it, how do I apply.',
    '- Useful detail is welcome. Repetition, source commentary, generic explanation, and filler are not.',
    '- A technically faithful but schematic list is not enough. The reader should be able to imagine the real job from the relationships between confirmed facts.',
    '- If the responsibilities, context, requirements, and conditions together contain enough source content, do not stop at a compact 250-350 word version. A longer ad is correct when every paragraph improves understanding.',
    '- For source-rich inputs, a Master below about 450 words is under-developed and will need revision; below about 500 words is usually still weak. Do not pad; instead use the available confirmed facts to explain work reality, handoffs, tools, candidate fit, conditions, and the offer with more continuity.',
    '- When source facts are rich, do not rely on one compact work paragraph. Use multiple paragraphs that each develop a different supported relationship: role context/result, core work flow, tools/handoffs, variability/autonomy, fit requirements, and conditions.',
    '- For source-rich inputs, responsibilities usually need more than one paragraph and should not be shorter than the conditions plus requirements combined. If the work paragraph is only a compressed inventory, expand it before finalizing.',
    '- Before finalizing, ask whether the same structure could be used for any warehouse, sales, or developer role after swapping keywords. If yes, rewrite the weakest section into more specific prose or remove it.',
    '',
    'Descriptive-writing rules:',
    '- Grounded expansion: when you add a descriptive sentence, it must be explainable from one plan block. If the sentence needs a fact that is not in the block, do not write it.',
    '- For example, debugging can support "analizzare un problema tecnico e lavorare alla correzione"; it does not authorize QA, production incidents, regressions, monitoring, releases, or external-service claims unless those facts appear in the plan.',
    '- For example, REST API can support "lavorare su integrazioni REST API"; it does not authorize third-party services, other services/altri servizi, endpoints, authentication, microservices, API design, query adaptation, data transformations, client/server discrepancy ownership, or end-to-end responsibility unless those facts appear in the plan.',
    '- For example, quantity checks and order preparation can support precision and coordination around goods and orders; they do not authorize transport documents, packaging, safety procedures, deliveries/consegne, or guaranteed delivery timings unless those facts appear in the plan.',
    '- Help the reader understand what the work feels like operationally through relationships between confirmed facts, not through fictional storytelling.',
    '- Prefer concrete verbs and specific nouns. Explain how activities connect to responsibilities and outcomes.',
    '- For technical roles, include the product/company context when available before describing the stack. Explain what is developed or maintained, where the stack is used, who collaborates with whom, and what technical responsibility the person owns. Do not leave the stack as an inventory.',
    '- For debugging, code review, integrations, quality, or analysis, explain what those facts mean operationally: understand the problem, identify where to intervene in the confirmed code area, work on REST API integrations when REST API is a fact, review code with other developers, coordinate with the product responsible when collaboration is confirmed, and keep code quality visible. Do this without inventing requirements clarification, solution design, integration verification, architecture ownership, process stages, or SLAs.',
    '- A technical role with frontend, backend, REST API, SQL, Git, debugging, code review, team collaboration, hybrid work, contract, and RAL has enough confirmed facts for a substantial ad. Do not return a compact one-page summary; expand the work and candidate-fit sections until the role is understandable.',
    '- Do not add architectural ownership, architecture decisions, system design responsibility, seniority scope, or technical leadership unless confirmed. If architecture is only an internal-learning fact, do not make it a responsibility or selection factor.',
    '- Do not add release coordination, deployment responsibility, sprint ceremonies, regular collaboration cadence, or process ownership unless confirmed. Git means version control, not release coordination, unless the ledger says so.',
    '- Debugging means analyzing and fixing problems. Do not expand it into testing, QA, test plans, automated tests, or application controls unless those duties are confirmed.',
    '- REST API integration does not imply external services, client-service discrepancy ownership, end-to-end ownership, regression prevention, or production incident handling unless confirmed.',
    '- For technical roles, keep existing architecture, product domain, internal procedures, and team operating habits out of the public copy unless they are explicitly REQUIRED, PREFERRED, or separately confirmed as public onboarding/training/working context. If they are only TRAINABLE/internal-learning facts, omit them.',
    '- Do not upgrade technology keywords into broader duties. "REST API" does not mean "progettazione di REST API" unless design is confirmed. "Database SQL" does not mean "mantenimento dei database SQL" unless database maintenance is confirmed.',
    '- For operational roles, connect place, tools, handoffs, constraints, and concrete activities so the role reads like work reality, not a warehouse of facts.',
    '- For warehouse and logistics roles, explain how incoming goods, quantity checks, storage, order preparation, handoffs, discrepancies, and transport coordination connect when those facts are present. Do not reduce them to one sentence of tasks.',
    '- For warehouse, logistics, production, or physical roles, do not add "sicurezza", "in sicurezza", DPI, procedure, normative, risk prevention, or safety responsibility unless those facts are confirmed. Physical work does not automatically imply a publishable safety requirement.',
    '- For logistics roles, keep checks at the confirmed level. If the ledger says quantity checks, write quantity checks; do not invent DDT, transport documents, order sheets, delivery notes, or other document sources unless confirmed.',
    '- For logistics roles, preparation of orders does not automatically mean packaging, boxing, wrapping, or confezionamento. Use only "preparazione degli ordini" unless those extra duties are confirmed.',
    '- Explain soft skills through the task or condition that makes them matter when that relationship is supported.',
    '- A requirements paragraph should answer "why these qualities matter here" using only confirmed facts. For warehouse/logistics examples, reliability and precision may be tied to quantity checks and order preparation; teamwork may be tied to confirmed collaboration with autisti/ufficio ordini; physical effort may be tied to confirmed carico/scarico or transpallet. Do not add new processes or outcomes.',
    '- Avoid empty adjectives such as dinamico, stimolante, leader, prestigioso, giovane, ambizioso, or opportunita di crescita unless the underlying claim is supported and useful.',
    '- Do not write giornata tipo, ogni giorno, prima/dopo, usually, often, or specific sequences unless cadence/sequence is actually supported.',
    '',
    'Length guidance:',
    '- Length follows source richness and candidate decision complexity, not seniority or prestige.',
    '- Operational roles: often about 500-750 words when confirmed facts support that depth.',
    '- Technical or professional roles: often about 600-900 words when confirmed facts support that depth; below about 450 words is usually too compressed when the ledger includes stack, responsibilities, team interaction, work mode, contract, and compensation.',
    '- Complex or managerial roles can be longer when distinct confirmed facts sustain the detail.',
    '- These are editorial targets, not quotas. If the confirmed facts do not support the range, write less rather than adding filler or inferred detail.',
    '',
    'The final fullText must read as a coherent Italian job ad for a candidate, never as a rubric, audit report, source commentary, or internal Horyzon document.',
  ].join('\n');
}
