import { ANNUNCI10X_AI_OUTPUT_SCHEMAS } from '../schemas.ts';
import { renderPrompt } from './helpers.ts';
import type { Annunci10xPromptDefinition } from './types.ts';

const invariants = [
  'Apply the smallest necessary conceptual revision.',
  'Revise against the immutable Truth Ledger and the Grounded Narrative Plan: RoleCard facts, RoleProfile, CommunicationStrategy, and groundedNarrativePlan. Never repair by inventing facts.',
  'Use groundedNarrativePlan.facts as the evidence plan. Keep or create only DIRECT, PARAPHRASE, or COMPOSITION claims grounded in KNOWN_FACT/MUST_MENTION_FACT entries.',
  'Use groundedNarrativePlan to preserve depth while removing overreach: keep explanations that are authorized by a plan block and remove or replace only the unsupported claim.',
  'When the validation issue is structural, template-like, or mechanical across the ad, rewrite whole paragraphs or sections as needed. Smallest necessary does not mean local word patches.',
  'When the validation issue is local, such as a mechanical CTA, revise only that local section. Do not rewrite, delete, or reorder unrelated supported sections.',
  'Do not introduce unsupported facts.',
  'Do not introduce or preserve safety, compliance, PPE, hazard, regulatory, procedure, or "in sicurezza" claims unless the Truth Ledger explicitly confirms them.',
  'Do not introduce or preserve logistics document names such as DDT, bolle, documenti di trasporto, delivery notes, or order documents unless the Truth Ledger explicitly confirms them.',
  'Do not introduce or preserve packaging, packing, wrapping, boxing, or "confezionamento/imballaggio" duties unless the Truth Ledger explicitly confirms them.',
  'Do not introduce or preserve release coordination, deployment ownership, or regular collaboration cadence unless the Truth Ledger explicitly confirms them.',
  'Do not introduce or preserve testing, QA, test automation, test cases, or "controlli applicativi" unless the Truth Ledger explicitly confirms testing duties.',
  'Do not introduce or preserve external services, client-service discrepancies, end-to-end ownership, regression prevention, or production incident scope unless the Truth Ledger explicitly confirms them.',
  'Preserve named tools exactly. If the Truth Ledger names "transpallet", do not replace it with a generic tool phrase.',
  'Unsupported or contradictory facts require confirmation and are not inserted or guessed.',
  'Fix candidate-facing editorial defects as well as factual validation issues.',
  'Turn RoleCard-like structure into natural recruiting copy. Do not preserve headings or phrasing that only exists because an internal field exists.',
  'When validation flags a schematic or card-like Master, rewrite the affected passages into connected Italian prose. Do not simply rename headings.',
  'When validation flags thin, condensed, or merely summarized copy, expand substantially using only confirmed facts and directly supported relationships. A correct revision may be much longer than the original.',
  'When validation flags candidate-fit or requirements as schematic, the repair is explanation, not a synonym swap: connect confirmed qualities to confirmed tasks, interactions, conditions, and problems.',
  'When an EDITORIAL claim with action REMOVE points to an entire redundant section, actually delete that section: include its id in changedSectionIds and omit that id from revisedSections.',
  'Remove missing-data disclosures entirely: do not write "non dichiarato", "non specificato", "non disponibile", or "non sono stati dichiarati".',
  'Remove invented application process details, employer branding, culture claims, benefits, training, or growth promises unless the Truth Ledger explicitly supports them.',
  'Remove internal/source/audit voice from public copy instead of explaining the internal problem to the candidate.',
  'Consolidate repeated facts and template-like filler while preserving useful role-specific detail.',
  'A section may be rewritten substantially when needed to restore natural candidate-facing prose; "smallest revision" does not mean preserving bad sentence structure.',
  'Preserve the semantic classification of required/preferred requirements and keep sourceFactIds traceable. TRAINABLE facts usually remain internal and should be omitted from public copy.',
  'PREFERRED facts may remain public as preferibile, gradito, plus, or non obbligatorio. TRAINABLE/internal-learning facts do not become public training promises, non-barrier claims, or public preferences. Remove "non serve conoscere", "si apprende sul posto", "viene acquisito nel ruolo", "utile familiarita", "conoscenza utile", and similar wording unless a separate confirmed public fact explicitly supports it.',
  'requiresValidation must be true because VALIDATE always follows REVISE.',
  'When an EDITORIAL validation claim uses action REMOVE for duplicated OPENING/MISSION content, actually delete one duplicated section: include its id in changedSectionIds and omit that id from revisedSections. Do not merely paraphrase both sections.',
  'TITLE is structural: its body should be an empty string. If validation flags a duplicated TITLE body, return the TITLE section with body empty.',
  'Every returned section must keep a non-empty candidate-facing title. Do not blank a section title while removing an internal label; replace it with a natural public heading.',
  'If validation flags an invented frequency or broadened duration, remove the invented cadence and restore only the bounded confirmed fact. Example: two-week onboarding stays two-week onboarding; never rewrite it as regular or ongoing interaction.',
  'Do not omit confirmed shifts or on-call availability while revising CONDITIONS, including explicit negative values such as no shifts and no on-call.',
  'Never solve repetition by deleting the only explicit confirmed mission/outcome. Keep one clear outcome statement and remove the redundant surrounding section/text instead.',
  'Preserve confirmed company context, operating context, autonomy, and unexpected events/variability when revising candidate-facing work-reality sections.',
  'If companyDescription or operatingContext is already present in the Master, preserve it unless validation specifically says it is unsupported. Never remove confirmed context while fixing an unrelated CTA.',
  'If companyDescription is missing from the Master and validation/gating reports it as omitted, restore it in the opening or first work paragraph instead of only editing later sections.',
  'Do not introduce frequency words such as quotidiano, ogni giorno, regolarmente, spesso, or recurring unless the Truth Ledger confirms that cadence.',
  'Do not introduce architecture choices, architectural ownership, system design, or technical leadership unless the Truth Ledger confirms those responsibilities.',
  'Do not assume that retaining a sourceFactId preserves a fact: its meaning must remain visible in title/body copy after the revision.',
  'When narrative context disagrees with a dedicated canonical RoleCard field, preserve the dedicated value and remove the discarded shadow value from candidate-facing copy.',
] as const;

export const REVISE_PROMPT: Annunci10xPromptDefinition = {
  id: 'annunci10x.revise',
  version: 'annunci10x.revise.v31',
  operationType: 'REVISE',
  outputSchema: ANNUNCI10X_AI_OUTPUT_SCHEMAS.REVISE,
  instructions: [
    renderPrompt('REVISE', 'Apply one targeted revision after factual or editorial validation, preserving only supported candidate-facing content.', invariants),
    '',
    'Revision priorities:',
    '- If validation flags a plausible but unsupported expansion, first locate the relevant groundedNarrativePlan block. Replace the claim with an allowed interpretation from that block or a closer paraphrase of the supporting facts; do not collapse the whole paragraph unless the whole paragraph is unsupported.',
    '- When replacing a claim, name the evidenceRefs mentally: use a DIRECT fact, a PARAPHRASE of one fact, or a COMPOSITION of multiple facts already in the plan. Do not replace with another professional inference.',
    '- If only the object/consequence is unsupported, keep the sentence structure and remove that object. For example, keep REST API as REST API without adding services/endpoints/query/transformations, requirements clarification, solution design, integration verification, regressions, QA, release/deploy, or architecture; keep order preparation or quantity checks at that level without adding deliveries, product-condition checks, documents, packaging, urgent peaks, procedures, or safety.',
    '- Preserve broad, human, candidate-facing prose. The fix for overreach is grounded replacement, not shrinking the Master into a list.',
    '- If validation flags source/audit/meta language, remove it completely and rewrite the affected passage directly for the candidate.',
    '- If validation flags missing-data language, delete that public sentence or section. Do not replace it with another placeholder.',
    '- If validation flags a mechanical CTA and no exact application destination exists, rewrite it as a neutral human invitation to apply without inventing process details, documents, experience summaries, availability, or saying "canale dell annuncio" / "canale dell\'annuncio" / "canale indicato nell annuncio" / "nell\'annuncio".',
    '- If the only validation issue is a mechanical CTA, return only the APPLICATION section in revisedSections and keep changedSectionIds limited to that section id.',
    '- If validation flags LinkedIn, CV, callbacks, interviews, selection steps, or response timing that are absent from applicationInstructions, remove them and use a neutral CTA.',
    '- If validation flags invented employer branding, training, benefits, growth, or culture, delete those claims rather than replacing them with another slogan.',
    '- If validation flags invented safety wording such as "sicurezza", "in sicurezza", procedures, PPE, or regulatory responsibility, remove that wording completely and keep only the confirmed physical task, tool, handoff, or condition.',
    '- If validation flags invented document references such as "documentazione di trasporto", "DDT", "bolle", "documentazione d ordine", or delivery notes, remove the document type and keep only the confirmed check (for example quantity or condition checks).',
    '- If validation flags invented packaging wording such as "confezionare", "imballare", "packing", "boxing", or "wrapping", remove that task and keep only the confirmed order preparation or handling fact.',
    '- If validation flags invented cadence or process scope such as "regolarmente", "ogni giorno", "coordinare le release", deployment ownership, or release coordination, remove that scope and keep only the confirmed collaboration, Git, code review, or debugging fact.',
    '- If validation flags invented testing or QA wording such as "test", "controlli applicativi", "test automation", or "verificare con test", remove it and keep only the confirmed debugging, correction, or integration fact.',
    '- If validation flags invented technical scope such as "servizi esterni", "discrepanze tra client e servizi", "end-to-end", "regressioni", or production incident handling, remove that scope and keep only the confirmed REST API, database SQL, debugging, or integration fact.',
    '- If a named tool such as "transpallet" was replaced by a generic phrase, restore the exact confirmed tool name.',
    '- If validation flags internal headings such as Missione del ruolo, Obiettivo del ruolo, Autonomia, Trainabile, Apprendibili, Apprendibile sul posto, Elementi apprendibili in sede, Conoscenze che si apprendono sul posto, Formabili in sede, Vincoli, negative constraints, or Contesto operativo e autonomia, fold the useful confirmed meaning into normal prose or remove it when it is not candidate-facing.',
    '- If validation flags a fact-sheet/list-only section, convert it into descriptive prose that connects confirmed activities, context, tools, conditions, and requirements without adding chronology or frequency.',
    '- If validation flags a thin or over-compressed Master, expand the opening, work, and candidate-fit sections enough for a candidate to understand what accepting the role would mean. Develop confirmed activities, handoffs, tools, problems, required qualities, conditions, and offer facts; do not add new benefits, processes, promises, frequency, or employer-brand claims.',
    '- If the claim references "master-depth", "troppo sintetico", "sotto-sviluppato", or similar, do not return a tiny local patch. Rewrite all under-developed public sections that carry the role: usually OPENING, RESPONSIBILITIES, REQUIREMENTS, and sometimes CONDITIONS. A good revision may add 250-450 words if supported by the Truth Ledger; preserve breadth with grounded explanations rather than shrinking to a list.',
    '- For source-rich depth revisions, aim for distinct developed sections: opening/context around 100-160 words, responsibilities/work reality around 230-360 words across multiple paragraphs, candidate fit around 110-180 words, and conditions clear enough for candidate decision. If the original is compact, return complete replacement sections, not small sentence patches.',
    '- If validation flags "La sezione requisiti/fit candidato è troppo schematica" or similar, rewrite the REQUIREMENTS section as a candidate-fit paragraph. Explain why each confirmed required quality matters in the actual work, using confirmed responsibilities and interactions as evidence. For example, precision may connect to quantity checks/order preparation, physical capacity to confirmed carico/scarico/transpallet, teamwork to confirmed collaboration with named interlocutors. Keep preferred facts as graditi/non obbligatori without adding benefits, faster onboarding, autonomy, productivity, or other consequences.',
    '- If requirements remain below about 110 words after a source-rich depth revision, assume the candidate-fit problem is not solved. Expand by explaining relationships between confirmed qualities and confirmed tasks, not by adding new requirements.',
    '- If responsibilities are flagged as condensed, expand them into connected prose with distinct paragraphs. Explain how confirmed activities, tools, interlocutors, checks, problems, and outcomes relate; do not merely add adjectives or repeat the same task list.',
    '- If validation flags duplication between OPENING and RESPONSIBILITIES, do not merely paraphrase both. Keep the opening focused on context, purpose, and role promise; move detailed tasks, tools, handoffs, discrepancies, debugging, or operational problems into RESPONSIBILITIES.',
    '- If validation flags an unnatural or malformed heading such as "Il ruolo è il contesto", replace only the heading with a natural candidate-facing title such as "Il ruolo" or "Il ruolo e il contesto".',
    '- If validation flags "Cosa serve" as HR-form wording, rewrite the body into a candidate-fit paragraph that explains why the confirmed qualities or skills matter in the actual work. Avoid "sono richieste" phrasing when it makes the section read like a form.',
    '- If validation flags keyword translation, replace keyword summaries with operational explanation. For example, debugging can become analysis of a malfunction and correction work; quantity control can become checking whether what arrived or is prepared matches what is expected. Keep the explanation at the level supported by the Truth Ledger.',
    '- If validation flags missing companyDescription or context, add or restore an opening that includes that confirmed context and then connect the responsibilities to it. Do not solve the issue by removing the opening.',
    '- If validation flags a duplicated responsibility prose/list structure, keep one natural responsibilities section and remove the redundant bullet-only section. Also remove dangling lead-in phrases such as "Attivita tipiche incluse nel ruolo:" when the separate list disappears.',
    '- If validation flags HR-form requirement blocks, replace the subheadings and bullet groups with a concise candidate-fit paragraph that preserves REQUIRED/PREFERRED meaning without changing strictness.',
    '- If validation flags a generic "Siamo ... e cerchiamo" opening, rewrite the opening around the confirmed role context, operating setting, and work result instead of using a company-first template.',
    '- If validation flags TRAINABLE/internal-learning facts presented as useful familiarity, implicit requirements, non-barriers, or training promises, delete that sentence unless a separate confirmed public training/onboarding fact supports a narrower replacement.',
    '- If validation flags REST API/database SQL overreach, restore the narrower supported fact. Use "REST API" without "progettazione" unless API design is confirmed; use "database SQL" without "mantenimento" unless database maintenance is confirmed.',
    '- If validation flags "Requisiti selettivi" or another requirement label that changes perceived strictness, rewrite the heading as "Cosa serve" or "Requisiti richiesti" and keep the confirmed required facts.',
    '- If validation flags repetition, keep the strongest occurrence and remove or merge the others. For OPENING/MISSION duplication, deletion is preferred over two paraphrases.',
    '- If validation flags template filler, replace it with a role-specific supported relationship or delete it.',
    '- If validation flags a material unresolved fact, remove the public claim rather than selecting one value. Do not surface "dato da chiarire" inside the Master.',
    '- If validation flags list-like responsibilities and source facts support relationships, rewrite the affected responsibility section as concise connected prose without inventing order or frequency.',
    '- Preserve confirmed conditions, compensation, requirements, and application instructions exactly in meaning.',
    '- Preserve confirmed companyDescription and operatingContext exactly in meaning. A revision must not make the Master lose the company context that was previously present.',
  ].join('\n'),
  invariants,
};
