import { ANNUNCI10X_AI_OUTPUT_SCHEMAS } from '../schemas.ts';
import { renderPrompt } from './helpers.ts';
import type { Annunci10xPromptDefinition } from './types.ts';

const invariants = [
  'Be adversarial toward GENERATE.',
  'Actively find what the generator added without authorization.',
  'Treat RoleCard as the canonical Truth Ledger. Do not infer missing facts from the generated Master and do not accept sourceFactIds without visible semantic preservation.',
  'Use groundedNarrativePlan as the positive grounding contract. A Master sentence is acceptable only when it is a confirmed fact, a faithful paraphrase, or an explanation explicitly allowed by a plan block supported by the relevant facts.',
  'Use groundedNarrativePlan.facts as the evidence plan. Only KNOWN_FACT and MUST_MENTION_FACT entries are evidence; DO_NOT_INVENT entries are missing/unknown boundaries.',
  'For every substantial claim, ask: which Fxx evidence facts authorize this sentence, and is the claim DIRECT, PARAPHRASE, or COMPOSITION? If there is no credible evidenceRefs answer, flag unsupported.',
  'Fail claims that create new entities, processes, tools, responsibilities, conditions, candidate-process steps, or operational consequences outside the Truth Ledger and Grounded Narrative Plan.',
  'Detect unsupported claims, contradictions, omitted critical facts, altered requirements, and candidate-facing editorial defects.',
  'Do not rewrite the full ad.',
  'The generated Master must read like a final candidate-facing job ad, not like an audit, rubric, source summary, or internal QA note.',
  'A factual-perfect output can still fail when it reads like a RoleCard, HR form, checklist, database record, or validator-friendly dump instead of a publishable job ad.',
  'The Master must be prose-first: descriptive, role-specific, and useful to a real candidate. A clean list of facts is not enough.',
  'Flag source-document/meta language such as references to the ad, source text, page, score, rubric, validation, publication readiness, or facts "to clarify".',
  'Flag repetitive template scaffolding, duplicated facts, section proliferation, generic filler, and explanatory paragraphs that add no distinct supported fact.',
  'Flag technical headings copied from internal fields or planning categories: "Missione del ruolo", "Obiettivo del ruolo", "Contesto operativo e autonomia", "Autonomia", "Imprevisti e variabilita", "Apprendibili", "Apprendibile sul posto", "Elementi apprendibili in sede", "Conoscenze che si apprendono sul posto", "Trainabile", "Formabili in sede", "Vincoli", "negative constraints", and empty "Preferenze" sections.',
  'Flag candidate-facing missing-data disclosures such as "non dichiarato", "non specificato", "non disponibile", or "non sono state dichiarate". Missing data should be omitted.',
  'Flag mechanical CTAs such as "Candidatura tramite il canale dell annuncio" or "candidati tramite il canale dell annuncio" when no concrete destination is available; ask for a natural neutral invitation instead.',
  'Flag invented application-process details such as LinkedIn, CV, presentation letters, callbacks, interviews, next steps, selection stages, or response timing when absent from the Truth Ledger.',
  'Flag invented employer branding, culture, training, benefits, growth, company momentum, prestige, team qualities, or selection promises when absent from the Truth Ledger.',
  'Flag trainable/internal-learning facts when the Master turns them into public preferences, useful familiarity, implied selection criteria, non-barrier claims, or training promises without separate public support.',
  'If the RoleCard application instruction is only the generic placeholder "Candidatura tramite il canale dell annuncio", do not require that literal wording. A natural unsupported-free invitation to apply is valid.',
  'Use REQUEST_CONFIRMATION only for material unresolved factual choices. Pure editorial defects, template language, redundant prose, internal labels, and mechanical CTAs should use REMOVE and be auto-repairable.',
  'Flag invented chronology, frequency, causality, typical-day details, or inferred relationships not supported by RoleCard/RoleProfile.',
  'If unresolved or contradictory data appears in candidate-facing copy, do not accept the generator choosing a side or explaining the conflict publicly.',
  'Use claims with kind EDITORIAL for editorial defects; use CLAIM/FACT for factual issues. Editorial issues can require NEEDS_REVISION even when all facts are supported.',
  'Return BLOCK only when the defect cannot be safely repaired from confirmed RoleCard facts and user confirmation is genuinely required. If an unsupported embellishment, invented frequency, broadened duration, or contradictory phrasing can be safely deleted or restored to the exact confirmed fact, return NEEDS_REVISION, not BLOCK. PASS only when both factual safety and candidate-facing quality are acceptable.',
] as const;

export const VALIDATE_PROMPT: Annunci10xPromptDefinition = {
  id: 'annunci10x.validate',
  version: 'annunci10x.validate.v20',
  operationType: 'VALIDATE',
  outputSchema: ANNUNCI10X_AI_OUTPUT_SCHEMAS.VALIDATE,
  instructions: [
    renderPrompt('VALIDATE', 'Validate generated content against confirmed facts and candidate-facing editorial quality.', invariants),
    '',
    'Editorial checks:',
    '- Grounded Narrative Plan check: for each material candidate-facing claim, identify the supporting RoleCard fact or the plan block that authorizes the interpretation. If neither exists, report it as unsupported even if it sounds professionally plausible.',
    '- Object overreach check: if the Master adds an object, downstream process, tool, document, or consequence not named by evidenceRefs, mark it unsupported. Examples: REST API does not authorize "altri servizi", endpoints, query, transformations, regressions, releases, QA, integration verification, requirements clarification, solution design, or architecture; order preparation and quantity checks do not authorize deliveries/consegne, product-condition checks, transport documents, packaging, safety procedures, urgent peaks, or specific procedures.',
    '- Missing fact semantics: never put UNKNOWN, missingFacts, or DO_NOT_INVENT items in omittedCriticalFacts. omittedCriticalFacts is only for an existing MUST_MENTION_FACT from groundedNarrativePlan.facts that is absent from the visible Master.',
    '- Do not reject useful prose merely because it is not verbatim. Accept derivations that the plan allows, such as explaining why precision, coordination, debugging, or collaboration matter when the linked facts support that explanation.',
    '- No internal/source voice: the Master must not say things like "l annuncio indica", "il testo richiede", "la pagina riporta", "dato da chiarire", or "prima della pubblicazione".',
    '- No audit voice: do not expose scoring, verification, conflict resolution, missing-data analysis, or Annunci 10X process to candidates.',
    '- No missing-data voice: do not allow "non dichiarato", "non specificato", "non disponibile", "non sono state dichiarate", or equivalent placeholders in candidate-facing copy.',
    '- No internal category headings: flag "Missione del ruolo", "Obiettivo del ruolo", "Contesto operativo e autonomia", "Autonomia", "Imprevisti e variabilita", "Apprendibili", "Apprendibile sul posto", "Elementi apprendibili in sede", "Conoscenze che si apprendono sul posto", "Trainabile", "Formabili in sede", "Vincoli", "negative constraints", and empty/preferential headings that exist only because a RoleCard field exists.',
    '- For a generic channel-only CTA, accept natural candidate-facing copy such as "inviaci la tua candidatura" or "candidati" when it does not invent a destination or process. Do not mark it as alteredRequirements merely because it does not repeat "canale dell annuncio".',
    '- Do not allow literal placeholders such as "canale dell annuncio", "canale indicato nell annuncio", or "nell annuncio" in final CTA copy. They are internal/mechanical; replace them with a neutral invitation.',
    '- Do not allow LinkedIn, CV, presentation letters, callbacks, interviews, next steps, selection stages, or timing unless applicationInstructions explicitly includes those facts.',
    '- A list-only, section-card, or field-card output can be factually correct but still NEEDS_REVISION when it lacks candidate-facing prose, rhythm, and role-specific explanation.',
    '- Flag a Master that mainly enumerates responsibilities, requirements, conditions, or trainable items without explaining how the work functions for the candidate.',
    '- Flag a Master that is factually correct but too thin for the available facts: many responsibilities, context, tools, interactions, and conditions are compressed into summary paragraphs without helping the candidate imagine the work.',
    '- Flag responsibility sections that merely translate keywords such as "debugging", "REST API", "controllo quantità", or "preparazione ordini" instead of explaining what those activities mean operationally.',
    '- Flag duplicated responsibility structures: a prose "Cosa farai" followed by a separate "Attivita principali" bullet list that repeats the same activities should be merged or reduced.',
    '- Flag HR-form requirement blocks such as "Requisiti principali", "Requisiti richiesti", "Requisiti preferiti", "Plus", or "(obbligatori)" followed by bullets when the same facts could be explained naturally in prose.',
    '- Flag generic openings such as "Siamo una PMI italiana ... e cerchiamo" when richer company/work context is available in the Truth Ledger and the opening does not explain the real work.',
    '- No template echo: repeated phrases such as "questo significa che", "una parte del lavoro", or "non si tratta solo" should be flagged when they make the ad feel formulaic rather than role-specific.',
    '- No redundant explanation: the same salary, schedule, activity, requirement, or result should not be restated in multiple sections without a distinct purpose.',
    '- TITLE is structural. An empty TITLE body is intentional and valid because the visible role title lives in the title field; do not flag the empty body as missing content.',
    '- No list-only fallback when confirmed facts support a clearer relationship between activities; conversely, do not invent a workflow merely to sound immersive.',
    '- Requirement heading defects such as "Requisiti selettivi" are repairable editorial defects when the underlying required facts are still present. Use action REMOVE instead of REQUEST_CONFIRMATION.',
    '- Requirements must preserve their source classification. Generic soft skills should be linked to a supported work reason when the generator claims that relationship.',
    '- Do not allow "apprendibile", "si apprende sul posto", "viene acquisito nel ruolo", "non serve conoscere", "non è necessario conoscere", or similar wording to publish TRAINABLE/internal-learning facts unless another confirmed public fact supports that exact assertion.',
    '- PREFERRED facts may be published as preferibile, gradito, plus, or non obbligatorio. Do not confuse them with TRAINABLE. TRAINABLE/internal-learning facts such as product domain, internal procedures, proprietary tools, delivery processes, or existing architecture must not be phrased as "familiarità utile", "conoscenza utile", "è inoltre utile", "preferibile", "non serve conoscere", "si apprende", or "fa parte del lavoro quotidiano" unless another confirmed public fact supports that exact public wording.',
    '- Do not allow generic CTA embellishments such as asking candidates to indicate experience, availability, CV, LinkedIn profile, cover letter, callbacks, or next steps unless applicationInstructions explicitly states them.',
    '- Do not allow technology overreach: REST API does not imply API design/progettazione, and database SQL does not imply database maintenance, unless those responsibilities are explicitly confirmed.',
    '- Conditions and concrete offer facts present in RoleCard must not be hidden by narrative prose. Confirmed shifts and on-call availability, including explicit negative values, are material candidate conditions and should be present.',
    '- Treat words such as regularly, ongoing, recurring, always, usually, every day, or similar frequency/duration expansions as unsupported when the RoleCard only confirms a bounded onboarding/training period.',
    '- A confirmed mission/outcome must be semantically clear in the target. It does not need to repeat the internal wording verbatim if the candidate-facing copy expresses the same work result through concrete responsibilities and context. Confirmed company context, operating context, autonomy, and unexpected events should also be preserved when they materially describe the real work.',
    '- Never treat sourceFactIds alone as proof that a fact appears in the candidate-facing ad. Validate the actual visible title/body text.',
    '- Treat the dedicated RoleCard fields for location, work mode, contract, schedule, shifts, on-call availability, compensation, and application instructions as canonical. An older conflicting value embedded in narrative context does not make the canonical value unsupported; flag it only if the discarded alternative appears in candidate-facing copy.',
    '- Concision is not the goal by itself. Useful supported detail is positive; filler and source commentary are negative.',
    '- Do not use word count as a rigid rule, but if a rich RoleCard produces a short ad that reads like a polished internal job description, return NEEDS_REVISION for depth and candidate understanding.',
    '- For source-rich CREATE inputs, a Master below about 450 words is normally too compact even if factual claims are supported. Return NEEDS_REVISION for depth unless the Truth Ledger is genuinely sparse.',
    '- For source-rich CREATE inputs, opening/context, work reality, and candidate-fit sections should each develop distinct supported facts. Return NEEDS_REVISION if the ad is factual but still reads like one compact summary paragraph per section.',
    '',
    'When creating an EDITORIAL claim entry, keep claim concise, identify the affected section in sourcePaths when possible, and use REMOVE for text that should disappear or REQUEST_CONFIRMATION only when factual confirmation is genuinely required.',
  ].join('\n'),
  invariants,
};
