export const ANNUNCI10X_METHOD_VERSION = 'annunci10x-method-v1';
export const ANNUNCI10X_RUBRIC_VERSION = 'annunci10x-rubric-v1';
export const ANNUNCI10X_STRATEGY_VERSION = 'annunci10x-strategy-v1';
export const ANNUNCI10X_PROMPT_PACK_VERSION = 'annunci10x-prompts-v1';
export const ANNUNCI10X_DATA_CONTRACT_VERSION = 'annunci10x-data-contracts-v1';
export const ANNUNCI10X_METHOD_VERSION_V2 = 'annunci10x-method-v2';
export const ANNUNCI10X_RUBRIC_VERSION_V2 = 'annunci10x-rubric-v2';
export const ANNUNCI10X_SCORE_SEMANTICS_VERSION_V2 = 'annunci10x-score-semantics-v2';

export const FACT_SOURCES = ['EXTRACTED', 'USER_DECLARED', 'SYSTEM_INFERRED', 'USER_CONFIRMED'] as const;
export const FACT_STATUSES = ['RAW', 'NORMALIZED', 'CONFIRMED', 'REJECTED', 'STALE'] as const;
export const ORIGINAL_AD_TYPES = ['PASTED_TEXT', 'UPLOADED_TEXT', 'MANUAL_BRIEF'] as const;
export const REQUIREMENT_CLASSIFICATIONS = ['REQUIRED', 'PREFERRED', 'TRAINABLE', 'DISQUALIFYING'] as const;
export const EMPHASIS_VALUES = ['LOW', 'MEDIUM', 'HIGH', 'UNKNOWN', 'NOT_APPLICABLE'] as const;
export const INTERVIEW_STEP_IDS = ['ROLE', 'OUTCOMES', 'REQUIREMENTS', 'CONDITIONS', 'ATTRACTION', 'CHANNEL'] as const;
export const SESSION_STATES = [
  'STARTED',
  'COLLECTING',
  'PRECHECKED',
  'ANALYZING',
  'ANALYSIS_READY',
  'CLARIFYING',
  'BUILDING',
  'ROLE_CARD_READY',
  'USER_CONFIRMED',
  'READY_FOR_PURCHASE',
  'PAYMENT_REQUIRED',
  'PURCHASE_PENDING',
  'ENTITLED',
  'GENERATING',
  'OUTPUT_READY',
  'NEEDS_VERIFICATION',
  'ERROR',
  'ABANDONED',
] as const;
export const EVALUATION_TARGET_KINDS = ['ORIGINAL_AD', 'GENERATED_MASTER', 'CHANNEL_VARIANT'] as const;
export const CHECK_STATUSES = ['PASS', 'PARTIAL', 'MISSING', 'CONFLICT', 'NOT_EVALUABLE'] as const;
export const PUBLICATION_STATUSES = ['READY', 'READY_WITH_WARNINGS', 'NEEDS_VERIFICATION', 'BLOCKED'] as const;
export const PUBLICATION_GATE_CODES = [
  'NO_BLOCKERS',
  'MISSING_REQUIRED_FACT',
  'UNSUPPORTED_CLAIM',
  'CONTRADICTED_CLAIM',
  'NEEDS_USER_CONFIRMATION',
  'LOW_COVERAGE',
  'MATERIAL_CONFLICT',
  'UNCONFIRMED_CLAIM',
  'CRITICAL_MISSING_DATA',
  'INVALID_CTA',
  'CHANNEL_INCONSISTENCY',
] as const;
export const GENERATED_SECTION_TYPES = [
  'TITLE',
  'OPENING',
  'CONTEXT',
  'MISSION',
  'RESPONSIBILITIES',
  'REQUIREMENTS',
  'CONDITIONS',
  'GROWTH',
  'APPLICATION',
  'CLAIM_CHECK',
] as const;
export const CLAIM_CHECK_STATUSES = ['SUPPORTED', 'NEEDS_CONFIRMATION', 'UNSUPPORTED', 'CONTRADICTED', 'NOT_APPLICABLE'] as const;
export const PUBLICATION_CHANNELS = ['LINKEDIN', 'INDEED', 'ATS', 'EMAIL', 'CUSTOM'] as const;
export const COMPARISON_CHANGE_TYPES = ['ADDED', 'REMOVED', 'REWRITTEN', 'CLARIFIED', 'NEEDS_REVIEW'] as const;
export const AI_OPERATION_TYPES = [
  'PRECHECK',
  'EXTRACT',
  'CLARIFY',
  'PROFILE',
  'STRATEGY',
  'GENERATE',
  'VALIDATE',
  'EVALUATE',
  'CHANNEL_ADAPTER',
  'EDIT_CLASSIFIER',
  'REVISE',
] as const;
export const AI_OPERATION_STATUSES = ['PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'SKIPPED'] as const;
export const ANNUNCI10X_ERROR_CODES = [
  'INVALID_INPUT',
  'SCHEMA_INVALID',
  'AI_PROVIDER_ERROR',
  'AI_INVALID_OUTPUT',
  'PAYMENT_REQUIRED',
  'ENTITLEMENT_MISSING',
  'GENERATION_BLOCKED',
  'NEEDS_VERIFICATION',
  'RATE_LIMITED',
  'INTERNAL',
  'INTERNAL_ERROR',
] as const;
export const PRODUCT_CODES = ['GUIDE', 'AD_GENERATION', 'GUIDE_PLUS_AD'] as const;
export const PURCHASE_STATUSES = ['PENDING', 'PAID', 'FAILED', 'REFUNDED', 'CANCELED'] as const;
export const ENTITLEMENT_SOURCES = ['PURCHASE', 'BUNDLE', 'ADMIN', 'OPEN_DECISION'] as const;
