import type { Metadata } from 'next';
import Link from 'next/link';
import { ProductStatus } from '@/components/product-status';
import { RadarStory } from '@/components/radar-story';
import { SiteFooter, SiteHeader } from '@/components/site-shell';
import { RADAR_URL, productCapabilities } from '@/content/product-truth';
import { departments } from '@/content/site-narrative';

export const metadata: Metadata = { title: 'Radar d’Impresa', description: 'Leggi cinque reparti, maturità dei processi, autonomia del titolare e adozione dell’AI.', alternates: { canonical: '/radar-impresa' } };
const outputs = [['Profilo complessivo','Una lettura d’insieme delle aree osservate.'],['Maturità dei processi','Quanto il lavoro dipende da metodi condivisi e ripetibili.'],['Autonomia del titolare','Quanto decisioni e attività risalgono ancora alla persona che guida.'],['Adozione dell’AI','Come l’AI è utilizzata e governata nel lavoro.']];

export default function RadarPage() {
 return <><SiteHeader/><main id="content" className="inside editorial-page narrative-page" data-page="radar-impresa"><nav className="editorial-breadcrumb" aria-label="Percorso di navigazione"><Link href="/">Horyzon</Link><span aria-hidden="true">/</span><span aria-current="page">Radar d’Impresa</span></nav><section className="inside-hero"><div><p className="eyebrow"><span/>Horyzon / Radar d’Impresa</p><h1>Leggi la tua impresa prima di cambiarla.</h1><p className="page-intro">Il Radar osserva cinque reparti, maturità dei processi, autonomia del titolare e adozione dell’AI.</p><div className="editorial-hero-actions"><a className="button primary" href={RADAR_URL}>Inizia il Radar <span aria-hidden="true">↗</span></a><a className="text-link" href="#pagina-contenuti">Scopri che cosa misura ↓</a></div><p className="fine-print">L’assessment si apre in Horyzon Hub.</p></div></section><div id="pagina-contenuti" className="editorial-body"/>
 <section className="narrative-section"><header><p className="section-kicker">Che cosa misura</p><h2>Una fotografia strutturata del punto di partenza.</h2><p className="narrative-lede">Il Radar qualifica l’impresa e mette in relazione cinque reparti con il modo in cui il lavoro è organizzato.</p></header><RadarStory/></section>
 <section className="narrative-section"><header><p className="section-kicker">Il sistema azienda</p><h2>Cinque reparti interdipendenti.</h2></header><div className="department-list">{departments.map(department=><article key={department.id}><h3>{department.name}</h3><p>{department.purpose}</p></article>)}</div></section>
 <section className="narrative-section"><header><p className="section-kicker">Gli output</p><h2>Quattro chiavi di lettura.</h2></header><div className="output-list">{outputs.map(([title,description])=><article key={title}><h3>{title}</h3><p>{description}</p></article>)}</div></section>
 <section className="narrative-section"><header><p className="section-kicker">Interpretazione</p><h2>Il contesto conta.</h2></header><p className="narrative-lede">La lettura considera il settore e rende visibili l’area più solida e quella prioritaria. Non è una diagnosi definitiva: prepara un confronto basato su evidenze.</p></section>
 <section className="narrative-section"><header><p className="section-kicker">Dopo il Radar</p><h2>Dal risultato alle prime priorità.</h2></header>{productCapabilities.slice(0,3).map(capability=><ProductStatus state={capability.state} key={capability.title}><h3>{capability.title}</h3><p>{capability.description}</p></ProductStatus>)}<p className="narrative-note">Il debrief Horyzon interpreta il risultato; organizzazione obiettivo, reparto prioritario e programma operativo vengono definiti e verificati nel percorso, non generati automaticamente dal questionario.</p></section>
 <section className="narrative-section"><header><p className="section-kicker">Limiti chiari</p><h2>Uno strumento di orientamento, non una promessa.</h2></header><p className="narrative-lede">Il Radar non sostituisce una diagnosi professionale, non produce da solo un piano di consulenza e non garantisce autonomia, profitti o automazione completa.</p><div className="narrative-actions"><a className="button primary" href={RADAR_URL}>Inizia il Radar <span aria-hidden="true">↗</span></a><Link className="text-link" href="/metodo">Comprendi il percorso Horyzon ↗</Link></div><p className="fine-print">Questo sito non trasferisce dati personali nel collegamento.</p></section></main><SiteFooter/></>;
}
