import Link from 'next/link';
import { RADAR_URL } from '@/content/product-truth';
import { departments, operatingJourney } from '@/content/site-narrative';
import { SiteHeader, SiteFooter } from './site-shell';
import { Journey } from './journey/journey';
import { JourneyContactForm } from './journey/contact-form';

export function Experience() {
 return <><SiteHeader/><main id="content" className="horyzon-home"><div className="journey-story" id="percorso"><Journey/><div className="journey-content">
  <section className="journey-chapter chapter-hero" id="orizzonte" aria-labelledby="hero-title"><div className="chapter-copy"><p className="chapter-label">HORYZON CONSULTING <span>/</span> DAL PRESENTE ALLA DIREZIONE</p><h1 id="hero-title">La tua impresa ha un orizzonte. <em>Rendiamolo operativo.</em></h1><p className="chapter-intro">Partiamo dalla realtà dell’azienda per costruire organizzazione, responsabilità e progresso misurabile.</p><div className="journey-actions"><a className="journey-button" href={RADAR_URL}>Inizia il Radar <span aria-hidden="true">↗</span></a><Link className="journey-link" href="/radar-impresa">Scopri che cosa misura</Link></div><p className="arrival-note">L’assessment si apre in Horyzon Hub, senza dati personali nel collegamento.</p></div><div className="chapter-caption"><span>DAL PUNTO IN CUI SEI.</span><span>VERSO CIÒ CHE PUOI DIVENTARE.</span></div></section>
  <section className="journey-chapter chapter-current" id="presente" aria-labelledby="current-title"><div className="chapter-copy"><p className="chapter-label">01 / IL PRESENTE</p><h2 id="current-title">Quando tutto passa dal titolare, <em>la crescita si ferma.</em></h2><p className="chapter-intro">Decisioni, clienti, problemi e conoscenza tornano sempre alla stessa persona. Il primo passo è rendere visibili dipendenze e colli di bottiglia.</p><ul className="discovery-words" aria-label="Segnali da osservare"><li>Decisioni accentrate</li><li>Ruoli poco chiari</li><li>Processi non condivisi</li><li>Dati frammentati</li></ul></div></section>
  <section className="journey-chapter chapter-discovery" id="radar" aria-labelledby="radar-home-title"><div className="chapter-copy"><p className="chapter-label">02 / IL RADAR</p><h2 id="radar-home-title">Leggere l’impresa. <em>Prima di cambiarla.</em></h2><p className="chapter-intro">Il Radar osserva cinque reparti, maturità dei processi, autonomia del titolare e adozione dell’AI.</p><p className="chapter-body">Restituisce un profilo complessivo, l’area più solida e quella prioritaria, con un’interpretazione coerente con il settore.</p><div className="journey-actions"><a className="journey-button" href={RADAR_URL}>Inizia il Radar <span aria-hidden="true">↗</span></a><Link className="journey-link" href="/radar-impresa">Come leggere il risultato</Link></div><p className="arrival-note">L’assessment si apre in Horyzon Hub.</p></div></section>
  <section className="journey-chapter chapter-dimensions" id="organismo" aria-labelledby="organism-title"><div className="chapter-copy"><p className="chapter-label">03 / L’ORGANISMO IMPRESA</p><h2 id="organism-title">Cinque reparti. <em>Una sola direzione.</em></h2><p className="chapter-intro">Amministrazione, Produzione, Commerciale, Marketing e Persone sono organi interdipendenti.</p><div className="dimension-paths department-paths">{departments.map((department,index)=><Link href="/le-tre-aree" key={department.id}><span className="dimension-number">{String(index+1).padStart(2,'0')}</span><div><h3>{department.name}</h3><p>{department.purpose}</p></div><span className="dimension-arrow" aria-hidden="true">↗</span></Link>)}</div></div></section>
  <section className="journey-chapter chapter-method" id="percorso-operativo" aria-labelledby="method-title"><div className="chapter-copy"><p className="chapter-label">04 / IL PERCORSO</p><h2 id="method-title">Dalla destinazione al <em>programma operativo.</em></h2><p className="chapter-intro">Disegniamo l’organizzazione obiettivo, confrontiamo ruoli e responsabilità, scegliamo il reparto prioritario e attiviamo soltanto ciò che può essere verificato.</p><ol className="journey-method">{operatingJourney.map((stage,index)=><li key={stage.title}><span>{String(index+1).padStart(2,'0')}</span>{stage.title}</li>)}</ol><Link href="/metodo" className="journey-link">Conosci il metodo Horyzon <span aria-hidden="true">↗</span></Link></div></section>
  <section className="journey-chapter chapter-infrastructure" id="infrastruttura" aria-labelledby="infrastructure-title"><div className="chapter-copy"><p className="chapter-label">05 / L’INFRASTRUTTURA</p><h2 id="infrastructure-title">Persone e AI. <em>Responsabilità distinte.</em></h2><p className="chapter-intro">Hub organizza discovery e Blueprint. Le persone e gli ambienti di lavoro approvati eseguono. Platform raccoglie KPI, report, snapshot ed evidenze di attivazione.</p><p className="chapter-body">L’AI sostiene il lavoro: non sostituisce la responsabilità né prende decisioni autonome per l’impresa.</p><Link className="journey-link" href="/piattaforma">Scopri la Platform <span aria-hidden="true">↗</span></Link></div></section>
  <section className="journey-chapter chapter-progress" id="progresso" aria-labelledby="progress-title"><div className="chapter-copy"><p className="chapter-label">06 / LA VERIFICA</p><h2 id="progress-title">Il cambiamento diventa <em>progresso misurabile.</em></h2><p className="chapter-intro">Indicatori, report, attività, sincronizzazioni ed evidenze mostrano che cosa è attivo, che cosa richiede intervento e quale priorità viene dopo.</p><p className="chapter-body">Nessuna promessa automatica: risultati e scostamenti orientano il ciclo successivo.</p></div></section>
  <section className="journey-chapter chapter-arrival" id="prossimo-orizzonte" aria-labelledby="arrival-title"><div className="chapter-copy"><p className="chapter-label">07 / IL PROSSIMO PASSO</p><h2 id="arrival-title">Comincia dal punto in cui <em>sei oggi.</em></h2><p className="chapter-intro">Avvia il Radar oppure raccontaci il reparto che oggi limita la direzione dell’impresa.</p><div className="journey-actions"><Link className="journey-button" href="/contatti">Parliamo della tua priorità <span aria-hidden="true">↗</span></Link></div></div></section>
  <section className="journey-further" aria-labelledby="further-title"><div><p className="chapter-label">LA PROSPETTIVA HORYZON</p><h2 id="further-title">Dietro il percorso,<br/><em>le persone.</em></h2></div><nav aria-label="Scopri Horyzon">{[['Horyzon','La nostra visione','/horyzon'],['Le persone','Le responsabilità nel percorso','/persone'],['La biblioteca','Idee da portare nel lavoro','/biblioteca'],['Entra in Horyzon','Il tuo talento, una missione comune','/entra-in-horyzon']].map(([title,description,href])=><Link href={href} key={href}><div><h3>{title}</h3><p>{description}</p></div><span aria-hidden="true">↗</span></Link>)}</nav></section>
  <section className="journey-contact-scene" id="parliamone"><JourneyContactForm/></section>
 </div></div></main><SiteFooter/></>;
}
