"use client";
import Link from "next/link";
import { motion, useScroll, useSpring, useTransform } from "motion/react";
import { useRef, useState } from "react";

const problems = [["01", "Tempo", "L’operatività assorbe le persone che dovrebbero guidare."], ["02", "Chiarezza", "I dati esistono, ma non diventano decisioni."], ["03", "Energia", "Processi frammentati rallentano talento e crescita."]];
const areas = [
  { n: "01", title: "Benessere organizzativo", text: "Persone, ruoli e processi allineati per rendere l’impresa più solida e meno dipendente dall’imprenditore.", href: "/benessere-organizzativo", tone: "lime" },
  { n: "02", title: "Benessere patrimoniale", text: "Il patrimonio torna a essere uno strumento di libertà, protezione e visione per chi lo ha creato.", href: "/benessere-patrimoniale", tone: "gold" },
  { n: "03", title: "Benessere digitale", text: "AI, automazioni e dati entrano nei processi reali: meno sprechi, più capacità decisionale.", href: "/benessere-digitale", tone: "cyan" },
];
function Wordmark() { return <Link href="/" className="wordmark" aria-label="Horyzon home"><span className="mark">H</span><span>HORYZON</span></Link>; }

export function Experience() {
  const story = useRef<HTMLElement>(null);
  const { scrollYProgress } = useScroll();
  const progress = useSpring(scrollYProgress, { stiffness: 90, damping: 24 });
  const { scrollYProgress: storyProgress } = useScroll({ target: story, offset: ["start end", "end start"] });
  const drift = useTransform(storyProgress, [0, 1], [120, -120]);
  const rotate = useTransform(storyProgress, [0, 1], [-10, 12]);
  const [menu, setMenu] = useState(false);
  return <main>
    <motion.div className="progress" style={{ scaleX: progress }} />
    <header className="nav"><Wordmark /><nav className={menu ? "navlinks open" : "navlinks"} aria-label="Navigazione principale"><a href="#evoluzione" onClick={() => setMenu(false)}>Metodo</a><a href="#soluzioni" onClick={() => setMenu(false)}>Soluzioni</a><a href="#umanita" onClick={() => setMenu(false)}>Visione</a><Link href="/contatti" className="nav-cta">Parliamone <span>↗</span></Link></nav><button className="menu" onClick={() => setMenu(!menu)} aria-label="Apri menu" aria-expanded={menu}>{menu ? "Chiudi" : "Menu"}</button></header>
    <section className="hero"><div className="aurora" aria-hidden="true"/><div className="grid" aria-hidden="true"/><motion.div className="hero-copy" initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .9 }}><p className="eyebrow"><span/> Impresa · Economia · Umanità</p><h1>Il futuro non si aspetta.<br/><em>Si organizza.</em></h1><p className="lead">Portiamo intelligenza, metodo e tecnologia dentro la tua azienda. Per trasformare il lavoro quotidiano in più risultati, più libertà, più futuro.</p><div className="hero-actions"><Link href="/contatti" className="button primary">Costruiamo il prossimo passo <span>↗</span></Link><a href="#evoluzione" className="button ghost">Scopri come <span>↓</span></a></div></motion.div><div className="orbit" aria-hidden="true"><div className="orbital o1"><i/></div><div className="orbital o2"><i/></div><div className="orbital o3"><i/></div><div className="core"><span>H</span><small>DIREZIONE</small></div></div><p className="scroll-hint">SCORRI PER VEDERE IL CAMBIAMENTO <span>↓</span></p></section>
    <section id="evoluzione" className="problem-section" ref={story}><motion.div className="section-orb" style={{ y: drift, rotate }}/><div className="section-head"><p className="eyebrow dark"><span/> Il punto di partenza</p><h2>La tua azienda non ha bisogno<br/>di altra complessità.</h2><p>Ha bisogno di vedere con chiarezza ciò che la rallenta e trasformarlo in una direzione concreta.</p></div><div className="problem-grid">{problems.map(([n,t,d], i) => <motion.article key={t} initial={{ opacity: 0, y: 40 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: "-15%" }} transition={{ delay: i*.12 }}><span>{n}</span><h3>{t}</h3><p>{d}</p><div className="signal"><b/><b/><b/><b/><b/></div></motion.article>)}</div><div className="turn"><span>Non partiamo da ciò che vendiamo.</span><strong>Partiamo da ciò che oggi<br/>ti impedisce di crescere.</strong></div></section>
    <section className="transformation"><div className="sticky-story"><p className="eyebrow"><span/> Il metodo Horyzon</p><h2>Dal rumore<br/><em>alla direzione.</em></h2><p>Osserviamo l’impresa come un sistema vivo. Leggiamo il problema, misuriamo le priorità e attiviamo soltanto le competenze necessarie.</p><div className="steps"><span className="active">01 ASCOLTO</span><span>02 MISURA</span><span>03 AZIONE</span></div></div><div className="system-visual" aria-label="Da segnali frammentati a direzione condivisa">{["Persone", "Processi", "Dati", "Decisioni", "Tecnologia", "Patrimonio"].map((x,i)=><motion.div className={`node n${i+1}`} key={x} initial={{ opacity:.25, scale:.7 }} whileInView={{ opacity:1, scale:1 }} viewport={{ once:true }} transition={{ delay:i*.1 }}>{x}</motion.div>)}<div className="system-core"><span>UNA SOLA</span><strong>DIREZIONE</strong></div></div></section>
    <section id="soluzioni" className="areas"><div className="section-head compact"><p className="eyebrow dark"><span/> Un solo interlocutore</p><h2>Tre dimensioni.<br/><em>Un’impresa intera.</em></h2></div><div className="area-list">{areas.map((a,i)=><motion.div key={a.title} className={`area ${a.tone}`} initial={{ opacity:0 }} whileInView={{ opacity:1 }} viewport={{ once:true }}><span className="area-n">{a.n}</span><div><h3>{a.title}</h3><p>{a.text}</p></div><Link href={a.href} aria-label={`Scopri ${a.title}`}>↗</Link><motion.div className="area-glow" initial={{ scale:0 }} whileInView={{ scale:1 }} transition={{ duration:.8, delay:i*.1 }}/></motion.div>)}</div></section>
    <section id="umanita" className="human"><div className="human-rings" aria-hidden="true"><span/><span/><span/><b>H</b></div><div className="human-copy"><p className="eyebrow"><span/> La nostra idea di futuro</p><h2>Tecnologia più potente.<br/><em>Persone più libere.</em></h2><p>L’intelligenza artificiale ha valore quando restituisce alle persone tempo, comprensione e possibilità. Il futuro che costruiamo non sostituisce l’umano: lo rimette al centro.</p><Link href="/umanita" className="text-link">Scopri la visione Horyzon <span>↗</span></Link></div></section>
    <section className="impact"><p className="eyebrow dark"><span/> Presenza e competenze</p><div className="impact-grid"><div><strong>50+</strong><span>professionisti</span></div><div><strong>3</strong><span>dimensioni integrate</span></div><div><strong>1</strong><span>direzione condivisa</span></div></div><p className="places">MILANO · MONZA · LUGANO · BELLINZONA · BARI · LECCE</p></section>
    <section className="final-cta"><div className="aurora"/><p>Il prossimo passo non è adottare più tecnologia.</p><h2>È capire dove può<br/><em>cambiare davvero la tua azienda.</em></h2><Link href="/contatti" className="button primary light">Parliamone <span>↗</span></Link></section>
    <footer><Wordmark/><p>Impresa · Economia · Umanità</p><div><Link href="/contatti">Contatti</Link><a href="mailto:info@horyzon.it">info@horyzon.it</a></div><small>© 2026 Horyzon Consulting</small></footer>
  </main>;
}
